apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: low-utilization-alert
  namespace: monitoring
spec:
  groups:
    - name: low-utilization-rules
      rules:
        - alert: LowCPUUsage
          expr: avg(rate(container_cpu_usage_seconds_total[5m])) BY (pod) < 0.1
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: "Pod {{ $labels.pod }} is underutilized"
            description: "Pod {{ $labels.pod }} is using less than 10% of its requested CPU."
