name: Terraform CI/CD

on:
  push:
    branches: [ main ]

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      # 1) Check out your repo
      - name: Check out
        uses: actions/checkout@v3

      # 2) Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

         # 3) Install gcloud CLI
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}   

      # 4) Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      # 5) Terraform Init
      - name: Terraform Init
        env:
          # Pass secrets to environment variables
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          GCP_REGION:     ${{ secrets.GCP_REGION }}
          CLUSTER_NAME:   ${{ secrets.CLUSTER_NAME }}
          PUB_SUB_SA:     ${{ secrets.PUB_SUB_SA }}
          SCALER_SA:      ${{ secrets.SCALER_SA }}
          TERRAFORM_SA:   ${{ secrets.TERRAFORM_SA }}
         
        run: |
          terraform init

      # 6) Terraform Plan
      - name: Terraform Plan
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          GCP_REGION:     ${{ secrets.GCP_REGION }}
          CLUSTER_NAME:   ${{ secrets.CLUSTER_NAME }}
          PUB_SUB_SA:     ${{ secrets.PUB_SUB_SA }}
          SCALER_SA:      ${{ secrets.SCALER_SA }}
          TERRAFORM_SA:   ${{ secrets.TERRAFORM_SA }}
         
        run: |
          terraform plan \
            -var="project_id=${GCP_PROJECT_ID}" \
            -var="region=${GCP_REGION}" \
            -var="cluster_name=${CLUSTER_NAME}" \
            -var="pub_sub_sa=${PUB_SUB_SA}" \
            -var="scaler_sa=${SCALER_SA}" \
            -var="terraform_sa=${TERRAFORM_SA}" \
            

      # 7) Terraform Apply (only if on main branch)
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          GCP_REGION:     ${{ secrets.GCP_REGION }}
          CLUSTER_NAME:   ${{ secrets.CLUSTER_NAME }}
          PUB_SUB_SA:     ${{ secrets.PUB_SUB_SA }}
          SCALER_SA:      ${{ secrets.SCALER_SA }}
          TERRAFORM_SA:   ${{ secrets.TERRAFORM_SA }}
          
        run: |
          terraform apply -auto-approve \
            -var="project_id=${GCP_PROJECT_ID}" \
            -var="region=${GCP_REGION}" \
            -var="cluster_name=${CLUSTER_NAME}" \
            -var="pub_sub_sa=${PUB_SUB_SA}" \
            -var="scaler_sa=${SCALER_SA}" \
            -var="terraform_sa=${TERRAFORM_SA}" \
           

